= Spring Boot, Camel and AMQ Online QuickStart

This quickstart shows how to connect a Spring-Boot application to an AMQ Online SaaS message broker and use JMS messaging between two Camel routes using OpenShift.



== Setting up the OpenShift environment

It is assumed that:

* Your OpenShift environment is configured for Fabric8 Maven Workflow, if not you can refer to my blog post https://github.com/rahmed-rh/fuse_on_OCP_7.5[Understand Fuse 7.5 on OpenShift]. 
** You can easily setup the fuse on openshift using script https://raw.githubusercontent.com/rahmed-rh/fuse_on_OCP_7.5/master/scripts/install_fis_7.5.sh[install_fis_7.5.sh]
* AMQ Online is installed on OpenShift environment,if not you can refer to my blog post https://github.com/rahmed-rh/amq-online[Understand AMQ Online]
** You can easily setup the AMQ Online on OpenShift using script https://raw.githubusercontent.com/rahmed-rh/amq-online/master/script/install-amq-online.sh[install-amq-online.sh]

To setup the test project you can run the following script.

TIP: If the project where the amq-online operator installed is not amq-online-infra project, then modify the name in the script (you need to have admin access to the project)   

[source,bash]
----
$ src/main/resources/openshift/create_demo_app.sh
----

IMPORTANT: After you run this command please take note of last two lines in output

For example output 

[source,bash]
----
oc get routes console -o 'jsonpath={.spec.host}' -n amq-online-infra
console-amq-online-infra.apps.cluster-91e5.sandbox671.opentlc.com <1>

oc get addressspace demo-space -o 'jsonpath={.status.endpointStatuses[?(@.name=="messaging")].externalHost}' -n amqp-demo
messaging-6c9efcc-amq-online-infra.apps.cluster-91e5.sandbox671.opentlc.com <2>
----
<1> Console Url, which you will use to see the queue, topics, connections,etc
<2> Messaging Endpoint which you will use to connect your application

== Running the example on Local Machine (Spring Boot)

. Modify the amqp.serviceName key in application.properties to the value you of Messaging Endpoint
. Then the following command will run the application

[source,bash]
----
mvn spring-boot:run -Dspring.profiles.active=dev
----

== Running the example in OpenShift

. The following command will package your app and run it on OpenShift:
+
[source,bash]
----
mvn fabric8:deploy -P openshift
----
+
. To list all the running pods:
+
[source,bash]
----
oc get pods
----

